### ISSUE TITLE
Can't build with maven

### ISSUE THREAD

**Issue by Abbotta4** [eternia16/javaGMR#35]
## Expected behavior ##
`mvn package` should build the jar in `target/`
## Actual behavior ##
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.957 s
[INFO] Finished at: 2019-04-08T22:35:25-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javaGMR: Could not resolve dependencies for project nl.hyranasoftware:javaGMR:jar:1.1.5: The following artifacts could not be resolved: com.github.plushaze.traynotification:TrayNotification:jar:0.3, nl.hyranasoftware:githubUpdater:jar:0.1: Could not find artifact com.github.plushaze.traynotification:TrayNotification:jar:0.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I have also tried cloning the linked repositories for [TrayNotification](https://github.com/PlusHaze/TrayNotification) and [githubupdater](https://github.com/eternia16/javaGithubUpdater/tree/0dea9a2652c888fec06971a51199c31f903a7229) and building those, but they fail their tests. Building with `-DskipTests`, installing the libraries with `mvn install:install-file -DpomFile=pom.xml` in each directory, and then attempting to build javaGMR with `mvn package` fails tests, and building with `-DskipTests` produces a .jar that causes an Exception:
```
user@host% java -jar javaGMR-1.1.5.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/Module
	at nl.hyranasoftware.javagmr.util.GMRLogger.logLine(GMRLogger.java:24)
	at nl.hyranasoftware.javagmr.gui.start(gui.java:34)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Exception running application nl.hyranasoftware.javagmr.gui
```
## Steps to reproduce the problem. (Optional) ##
`mvn package`
## What Operating system do you use, and what file did you download? (DMG, EXE, or JAR) ##
I am using Arch Linux and attempting to build from source with Maven

I could be doing this all wrong, but I figure it was worth asking, as I couldn't find build instructions. Thank you.

**Comment by winny-** [comment]
Hi! Could you comment how you resolved this issue? I ran into this as well - and likely somebody else will too :)

**Comment by William-Moriarty** [comment]
Looks like Im one of those. Same issue. Wont build with maven.
